from tenant_watch.permissions.address_permissions import CanListCreateWatchAddressPermission, CanRetrieveUpdateDestroyWatchAddressPermission
from tenant_watch.permissions.contact_permissions import CanListCreateWatchContactPermission, CanRetrieveUpdateDestroyWatchContactPermission
from tenant_watch.permissions.comment_permissions import CanListCreateWatchCommentPermission, CanRetrieveUpdateDestroyWatchCommentPermission
from tenant_watch.permissions.metric_permissions import CanListCreateWatchMetricPermission, CanRetrieveUpdateDestroyWatchMetricPermission
from tenant_watch.permissions.file_upload_permissions import CanListCreateWatchFileUploadPermission, CanRetrieveUpdateDestroyWatchFileUploadPermission
from tenant_watch.permissions.base_permissions import CanListCreateWatchPermission, CanRetrieveUpdateDestroyWatchPermission
