from tenant_foundation.views.tags.list_create_views import TagListCreateAPIView
from tenant_foundation.views.tags.retrieve_update_delete_views import TagRetrieveUpdateDestroyAPIView
from tenant_foundation.views.how_did_you_hear.list_create_views import HowHearAboutUsItemListCreateAPIView
from tenant_foundation.views.how_did_you_hear.retrieve_update_delete_views import HowHearAboutUsItemRetrieveUpdateDestroyAPIView
