from tenant_foundation.views.tags.list_create_views import TagListCreateAPIView
from tenant_foundation.views.tags.retrieve_update_delete_views import TagRetrieveUpdateDestroyAPIView

from tenant_foundation.views.how_did_you_hear.list_create_views import HowHearAboutUsItemListCreateAPIView
from tenant_foundation.views.how_did_you_hear.retrieve_update_delete_views import HowHearAboutUsItemRetrieveUpdateDestroyAPIView

from tenant_foundation.views.expectation_item.list_create_views import ExpectationItemListCreateAPIView
from tenant_foundation.views.expectation_item.retrieve_update_delete_views import ExpectationItemRetrieveUpdateDestroyAPIView

from tenant_foundation.views.meaning.list_create_views import MeaningItemListCreateAPIView
from tenant_foundation.views.meaning.retrieve_update_delete_views import MeaningItemRetrieveUpdateDestroyAPIView

from tenant_foundation.views.score_point.list_create_views import ScorePointListCreateAPIView
from tenant_foundation.views.score_point.retrieve_update_delete_views import ScorePointRetrieveUpdateDestroyAPIView

from tenant_foundation.views.badge.list_create_views import BadgeListCreateAPIView
from tenant_foundation.views.badge.retrieve_update_delete_views import BadgeRetrieveUpdateDestroyAPIView

from tenant_foundation.views.award.list_create_views import AwardListCreateAPIView
from tenant_foundation.views.award.retrieve_update_delete_views import AwardRetrieveUpdateDestroyAPIView

from tenant_foundation.views.district.list_create_views import DistrictListCreateAPIView
from tenant_foundation.views.district.retrieve_update_delete_views import DistrictRetrieveUpdateDestroyAPIView
