from tenant_private_file_upload.views.list_create_views import PrivateFileUploadListCreateAPIView
from tenant_private_file_upload.views.retrieve_update_destroy_views import PrivateFileUploadRetrieveUpdateDestroyAPIView
