from tenant_foundation.serializers.tags.list_create_serializers import TagListCreateSerializer
from tenant_foundation.serializers.tags.retrieve_update_serializers import TagRetrieveUpdateDestroySerializer

from tenant_foundation.serializers.how_did_you_hear.list_create_serializers import HowHearAboutUsItemListCreateSerializer
from tenant_foundation.serializers.how_did_you_hear.retrieve_update_serializers import HowHearAboutUsItemRetrieveUpdateDestroySerializer

from tenant_foundation.serializers.expectation_item.list_create_serializers import ExpectationItemListCreateSerializer
from tenant_foundation.serializers.expectation_item.retrieve_update_serializers import ExpectationItemRetrieveUpdateDestroySerializer

from tenant_foundation.serializers.meaning.list_create_serializers import MeaningItemListCreateSerializer
from tenant_foundation.serializers.meaning.retrieve_update_serializers import MeaningItemRetrieveUpdateDestroySerializer

from tenant_foundation.serializers.score_point.list_serializer import ScorePointListSerializer
from tenant_foundation.serializers.score_point.create_serializer import ScorePointCreateSerializer
from tenant_foundation.serializers.score_point.retrieve_serializer import ScorePointRetrieveSerializer

from tenant_foundation.serializers.badge.list_serializer import BadgeListSerializer
from tenant_foundation.serializers.badge.create_serializer import BadgeCreateSerializer
from tenant_foundation.serializers.badge.retrieve_serializer import BadgeRetrieveSerializer

from tenant_foundation.serializers.award.list_serializer import AwardListSerializer
from tenant_foundation.serializers.award.create_serializer import AwardCreateSerializer
from tenant_foundation.serializers.award.retrieve_serializer import AwardRetrieveSerializer
