from tenant_foundation.serializers.tags.list_create_serializers import TagListCreateSerializer
from tenant_foundation.serializers.tags.retrieve_update_serializers import TagRetrieveUpdateDestroySerializer
from tenant_foundation.serializers.how_did_you_hear.list_create_serializers import HowHearAboutUsItemListCreateSerializer
from tenant_foundation.serializers.how_did_you_hear.retrieve_update_serializers import HowHearAboutUsItemRetrieveUpdateDestroySerializer
from tenant_foundation.serializers.expectation_item.list_create_serializers import ExpectationItemListCreateSerializer
from tenant_foundation.serializers.expectation_item.retrieve_update_serializers import ExpectationItemRetrieveUpdateDestroySerializer
