from tenant_foundation.serializers.tags.list_create_serializers import TagListCreateSerializer
from tenant_foundation.serializers.tags.retrieve_update_serializers import TagRetrieveUpdateDestroySerializer
