from tenant_staff.permissions.comment_permissions import CanListCreateStaffCommentPermission, CanRetrieveUpdateDestroyStaffCommentPermission
from tenant_staff.permissions.file_upload_permissions import CanListCreateStaffFileUploadPermission, CanRetrieveUpdateDestroyStaffFileUploadPermission
from tenant_staff.permissions.base_permissions import CanListCreateStaffPermission, CanRetrieveUpdateDestroyStaffPermission
from tenant_staff.permissions.node_permissions import CanListCreateStaffNodePermission, CanRetrieveUpdateDestroyStaffNodePermission
