from tenant_staff.permissions.address_permissions import CanListCreateStaffAddressPermission, CanRetrieveUpdateDestroyStaffAddressPermission
from tenant_staff.permissions.contact_permissions import CanListCreateStaffContactPermission, CanRetrieveUpdateDestroyStaffContactPermission
from tenant_staff.permissions.comment_permissions import CanListCreateStaffCommentPermission, CanRetrieveUpdateDestroyStaffCommentPermission
from tenant_staff.permissions.metric_permissions import CanListCreateStaffMetricPermission, CanRetrieveUpdateDestroyStaffMetricPermission
from tenant_staff.permissions.file_upload_permissions import CanListCreateStaffFileUploadPermission, CanRetrieveUpdateDestroyStaffFileUploadPermission
from tenant_staff.permissions.base_permissions import CanListCreateStaffPermission, CanRetrieveUpdateDestroyStaffPermission
