from tenant_private_image_upload.serializers.list_serializers import PrivateImageUploadListSerializer
from tenant_private_image_upload.serializers.create_serializers import PrivateImageUploadCreateSerializer
from tenant_private_image_upload.serializers.retrieve_serializers import PrivateImageUploadRetrieveSerializer
from tenant_private_image_upload.serializers.update_serializers import PrivateImageUploadUpdateSerializer
