# Generated by Django 2.2.1 on 2019-05-29 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared_foundation', '0003_auto_20190529_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='The unique slug used for this district when accessing the details page.', max_length=127, unique=True, verbose_name='Slug')),
                ('name', models.CharField(db_index=True, help_text='The name of the district.', max_length=63, unique=True, verbose_name='Name')),
                ('tenant', models.ForeignKey(help_text='The tenant this district belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='shared_foundation.SharedOrganization')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'db_table': 'nwapp_districts',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
