# Generated by Django 2.2.7 on 2019-11-22 01:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_foundation', '0004_shareduser_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, help_text='The text content of this item.', max_length=127, unique=True, verbose_name='Text')),
                ('sort_number', models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, help_text='The number this item will appear when sorted by number.', verbose_name='Sort #')),
                ('is_for_associate', models.BooleanField(blank=True, default=True, help_text='Indicates this option will be visible for the associate.', verbose_name='Is for associate')),
                ('is_for_customer', models.BooleanField(blank=True, default=True, help_text='Indicates this option will be visible for the customer.', verbose_name='Is for customer')),
                ('is_for_staff', models.BooleanField(blank=True, default=True, help_text='Indicates this option will be visible for the staff.', verbose_name='Is for staff')),
                ('is_for_partner', models.BooleanField(blank=True, default=True, help_text='Indicates this option will be visible for the partner.', verbose_name='Is for partner')),
                ('is_archived', models.BooleanField(blank=True, db_index=True, default=False, help_text='Indicates whether how hear item was archived.', verbose_name='Is Archived')),
            ],
            options={
                'verbose_name': 'What do you expect from NW Item',
                'verbose_name_plural': 'What do you expect from NW Items',
                'db_table': 'nwapp_expectation_items',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='HowHearAboutUsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, help_text='The text content of this item.', max_length=127, unique=True, verbose_name='Text')),
                ('sort_number', models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, help_text='The number this item will appear when sorted by number.', verbose_name='Sort #')),
                ('is_for_associate', models.BooleanField(blank=True, default=True, help_text='Indicates this option will be visible for the associate.', verbose_name='Is for associate')),
                ('is_for_customer', models.BooleanField(blank=True, default=True, help_text='Indicates this option will be visible for the customer.', verbose_name='Is for customer')),
                ('is_for_staff', models.BooleanField(blank=True, default=True, help_text='Indicates this option will be visible for the staff.', verbose_name='Is for staff')),
                ('is_for_partner', models.BooleanField(blank=True, default=True, help_text='Indicates this option will be visible for the partner.', verbose_name='Is for partner')),
                ('is_archived', models.BooleanField(blank=True, db_index=True, default=False, help_text='Indicates whether how hear item was archived.', verbose_name='Is Archived')),
            ],
            options={
                'verbose_name': 'How Hear About Us Item',
                'verbose_name_plural': 'How Hear About Us Items',
                'db_table': 'nwapp_how_hear_about_us_items',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MeaningItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, help_text='The text content of this item.', max_length=127, unique=True, verbose_name='Text')),
                ('sort_number', models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, help_text='The number this item will appear when sorted by number.', verbose_name='Sort #')),
                ('is_for_associate', models.BooleanField(blank=True, default=True, help_text='Indicates this option will be visible for the associate.', verbose_name='Is for associate')),
                ('is_for_customer', models.BooleanField(blank=True, default=True, help_text='Indicates this option will be visible for the customer.', verbose_name='Is for customer')),
                ('is_for_staff', models.BooleanField(blank=True, default=True, help_text='Indicates this option will be visible for the staff.', verbose_name='Is for staff')),
                ('is_for_partner', models.BooleanField(blank=True, default=True, help_text='Indicates this option will be visible for the partner.', verbose_name='Is for partner')),
                ('is_archived', models.BooleanField(blank=True, db_index=True, default=False, help_text='Indicates whether how hear item was archived.', verbose_name='Is Archived')),
            ],
            options={
                'verbose_name': 'What does NW mean to you Item',
                'verbose_name_plural': 'What does NW mean to you Items',
                'db_table': 'nwapp_meaning_items',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(help_text='The user whom is a member.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='member', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('indexed_text', models.CharField(blank=True, db_index=True, help_text='The searchable content text used by the keyword searcher function.', max_length=511, null=True, unique=True, verbose_name='Indexed Text')),
                ('type_of', models.PositiveSmallIntegerField(choices=[('business', 'Business'), ('residential', 'Residential'), ('community_cares', 'Community Cares')], db_index=True, help_text='The type of member this is.', verbose_name='Type of')),
                ('state', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', help_text='The state of this member.', max_length=15, verbose_name='State')),
                ('deactivation_reason', models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Blacklisted'), (3, 'Moved'), (4, 'Deceased'), (5, 'Do not contact'), (0, 'Not specified'), (1, 'Other')], default=0, help_text='The reason why this member was deactivated.', verbose_name='Deactivation reason')),
                ('deactivation_reason_other', models.CharField(blank=True, default='', help_text='The reason why this member was deactivated which was not in the list.', max_length=2055, verbose_name='Deactivation reason (other)')),
                ('created_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the creator.', null=True, verbose_name='Created from')),
                ('created_from_is_public', models.BooleanField(blank=True, default=False, help_text='Is creator a public IP and is routable.', verbose_name='Is the IP ')),
                ('last_modified_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the modifier.', null=True, verbose_name='Last modified from')),
                ('last_modified_from_is_public', models.BooleanField(blank=True, default=False, help_text='Is modifier a public IP and is routable.', verbose_name='Is the IP ')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user whom created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user whom modified this object last.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'nwapp_members',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, help_text='The text content of this tag.', max_length=31, unique=True, verbose_name='Text')),
                ('description', models.TextField(blank=True, default='', help_text='A short description of this tag.', null=True, verbose_name='Description')),
                ('is_archived', models.BooleanField(blank=True, db_index=True, default=False, help_text='Indicates whether tag was archived.', verbose_name='Is Archived')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'nwapp_tags',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MemberMetric',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tenant_foundation.Member')),
                ('how_hear_other', models.CharField(blank=True, default='Did not answer', help_text='How member heared/learned about this NWApp.', max_length=2055, verbose_name='Learned about us (other)')),
                ('expectation_other', models.CharField(blank=True, default='Did not answer', help_text='-', max_length=2055, verbose_name='What do you expect from NW? (other)')),
                ('meaning_other', models.CharField(blank=True, default='Did not answer', help_text='-', max_length=2055, verbose_name='What does NW mean to you? (other)')),
                ('volunteer', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No'), (2, 'Maybe')], default=2, help_text='Are you willing to volunteer as a area coordinator / associate', verbose_name='Willing to volunteer?')),
                ('gender', models.CharField(blank=True, help_text='Gender of the person. While `Male` and `Female` may be used, text strings are also acceptable for people who do not identify as a binary gender.', max_length=31, null=True, verbose_name='Gender')),
                ('year_of_birth', models.PositiveSmallIntegerField(blank=True, default=0, help_text='The year that this member was born in.', verbose_name='Year of Birth')),
                ('organization_employee_count', models.PositiveSmallIntegerField(blank=True, default=0, help_text="The employee count at this member's organization.", verbose_name='Organization Employee Count')),
                ('organization_founding_year', models.PositiveSmallIntegerField(blank=True, default=0, help_text='The year this organization was founded.', verbose_name='Organization Founding Year')),
                ('organization_type_of', models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Private'), (3, 'Government'), (4, 'Non-Profit'), (1, 'Unspecified')], default=1, help_text='The type of organization this is based on Neighbourhood Watch Canada internal classification.', verbose_name='Organization Type of')),
                ('created_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the creator.', null=True, verbose_name='Created from')),
                ('created_from_is_public', models.BooleanField(blank=True, default=False, help_text='Is creator a public IP and is routable.', verbose_name='Is the IP ')),
                ('last_modified_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the modifier.', null=True, verbose_name='Last modified from')),
                ('last_modified_from_is_public', models.BooleanField(blank=True, default=False, help_text='Is modifier a public IP and is routable.', verbose_name='Is the IP ')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user whom created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_member_metrics', to=settings.AUTH_USER_MODEL)),
                ('expectation', models.ForeignKey(blank=True, help_text='What do you expect from NW?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_metric_expectations', to='tenant_foundation.ExpectationItem')),
                ('how_hear', models.ForeignKey(blank=True, help_text='How the member heard about the NWApp.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_metric_how_hear_items', to='tenant_foundation.HowHearAboutUsItem')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user whom modified this object last.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_member_metrics', to=settings.AUTH_USER_MODEL)),
                ('meaning', models.ForeignKey(blank=True, help_text='What does NW mean to you?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_metric_meanings', to='tenant_foundation.MeaningItem')),
                ('tags', models.ManyToManyField(blank=True, help_text='The tags associated with this member.', related_name='member_metric_tags', to='tenant_foundation.Tag')),
            ],
            options={
                'verbose_name': 'Member Metric',
                'verbose_name_plural': 'Members Metrics',
                'db_table': 'nwapp_member_metrics',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MemberContact',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tenant_foundation.Member')),
                ('is_ok_to_email', models.BooleanField(blank=True, default=True, help_text='Indicates whether member allows being reached by email', verbose_name='Is OK to email')),
                ('is_ok_to_text', models.BooleanField(blank=True, default=True, help_text='Indicates whether member allows being reached by text.', verbose_name='Is OK to text')),
                ('organization_name', models.CharField(blank=True, help_text='The name of the organization or business this person represents.', max_length=255, null=True, verbose_name='Organization Name')),
                ('first_name', models.CharField(blank=True, help_text="The member's given name.", max_length=63, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text="The member's sure name.", max_length=63, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Email address.', max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Invalid email')], verbose_name='Email')),
                ('primary_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='The primary telephone number used by the member.', max_length=128, null=True, region=None, verbose_name='Primary Telephone')),
                ('secondary_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='The secondary or other telephone number used by the member.', max_length=128, null=True, region=None, verbose_name='Secondary Telephone')),
                ('created_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the creator.', null=True, verbose_name='Created from')),
                ('created_from_is_public', models.BooleanField(blank=True, default=False, help_text='Is creator a public IP and is routable.', verbose_name='Is the IP ')),
                ('last_modified_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the modifier.', null=True, verbose_name='Last modified from')),
                ('last_modified_from_is_public', models.BooleanField(blank=True, default=False, help_text='Is modifier a public IP and is routable.', verbose_name='Is the IP ')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user whom created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_member_contacts', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user whom modified this object last.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_member_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Contact',
                'verbose_name_plural': 'Member Contacts',
                'db_table': 'nwapp_member_contacts',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MemberAddress',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tenant_foundation.Member')),
                ('country', models.CharField(help_text='The country. For example, USA. You can also provide the two-letter <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements">ISO 3166-1 alpha-2</a> country code.', max_length=127, verbose_name='Country')),
                ('region', models.CharField(help_text='The region. For example, CA.', max_length=127, verbose_name='Region')),
                ('locality', models.CharField(help_text='The locality. For example, Mountain View.', max_length=127, verbose_name='Locality')),
                ('street_number', models.CharField(blank=True, help_text='-', max_length=127, null=True, verbose_name='Street Number')),
                ('street_name', models.CharField(blank=True, help_text='-', max_length=127, null=True, verbose_name='Street Name')),
                ('apartment_unit', models.CharField(blank=True, help_text='-', max_length=127, null=True, verbose_name='Apartment Unit')),
                ('street_type', models.CharField(blank=True, help_text='-', max_length=127, null=True, verbose_name='Region')),
                ('street_type_other', models.CharField(blank=True, help_text='-', max_length=127, null=True, verbose_name='Street Type Other')),
                ('street_direction', models.CharField(blank=True, help_text='-', max_length=127, null=True, verbose_name='Street Direction')),
                ('postal_code', models.CharField(blank=True, help_text='-', max_length=32, null=True, verbose_name='Postal Code')),
                ('created_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the creator.', null=True, verbose_name='Created from')),
                ('created_from_is_public', models.BooleanField(blank=True, default=False, help_text='Is creator a public IP and is routable.', verbose_name='Is the IP ')),
                ('last_modified_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the modifier.', null=True, verbose_name='Last modified from')),
                ('last_modified_from_is_public', models.BooleanField(blank=True, default=False, help_text='Is modifier a public IP and is routable.', verbose_name='Is the IP ')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user whom created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_member_addresses', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user whom modified this object last.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_member_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Address',
                'verbose_name_plural': 'Member Addresses',
                'db_table': 'nwapp_member_addresses',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
