# Generated by Django 2.2.7 on 2019-11-29 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercontact',
            name='primary_phone',
            field=models.CharField(blank=True, help_text='The primary telephone number used by the member.', max_length=31, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Primary Telephone'),
        ),
        migrations.AlterField(
            model_name='membercontact',
            name='secondary_phone',
            field=models.CharField(blank=True, help_text='The secondary or other telephone number used by the member.', max_length=31, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Secondary Telephone'),
        ),
    ]
