# Generated by Django 2.2.7 on 2020-02-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='text',
        ),
        migrations.AddField(
            model_name='item',
            name='can_be_posted_on_social_media',
            field=models.BooleanField(blank=True, default=True, help_text='Has the poster allowed this item be posted on social media?', verbose_name='Can be posted on Social Media?'),
        ),
        migrations.AddField(
            model_name='item',
            name='external_url',
            field=models.URLField(blank=True, default='', help_text='The URL for the item to reference an external address.', max_length=63, null=True, verbose_name='External URL'),
        ),
        migrations.AddField(
            model_name='item',
            name='finish_at',
            field=models.DateTimeField(blank=True, help_text='The date and time this item will finish if it is an event.', null=True, verbose_name='Finish at'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_all_day_event',
            field=models.BooleanField(blank=True, default=False, help_text='Is this event item full day?', verbose_name='Is all day event'),
        ),
        migrations.AddField(
            model_name='item',
            name='shown_to_whom',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'General Public'), (3, 'All NW Staff'), (4, 'My Watch Area')], help_text='The person / organization that is allowed to view this item.', null=True, verbose_name='Shown to whom?'),
        ),
        migrations.AddField(
            model_name='item',
            name='start_at',
            field=models.DateTimeField(blank=True, help_text='The date and time this item will start if it is an event.', null=True, verbose_name='Start at'),
        ),
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', help_text='The state of this item.', max_length=15, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, default='', help_text='The title of the item, if it has one.', max_length=63, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='', help_text='A short description of this item, if it has one.', null=True, verbose_name='Description'),
        ),
    ]
