# Generated by Django 2.2.7 on 2020-02-02 04:37

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetaddressrange',
            name='street_numbers',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, help_text='Please select the range of street numbers. Note: Internal implementation.', null=True, verbose_name='Street Numbers'),
        ),
    ]
