# Generated by Django 2.2.7 on 2020-03-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='watch',
            name='archive_reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'No Area Coordinator'), (3, 'Watch has collectively opted out of program'), (4, 'Watch Area not compliant'), (1, 'Other'), (0, 'Not specified')], default=0, help_text='The reason why this watch was archived.', verbose_name='Archive reason'),
        ),
        migrations.AddField(
            model_name='watch',
            name='archive_reason_other',
            field=models.CharField(blank=True, default='', help_text='The reason why this watch was archived which was not in the list.', max_length=2055, null=True, verbose_name='Archive reason (other)'),
        ),
        migrations.AddField(
            model_name='watch',
            name='state',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', help_text='The state of this watch.', max_length=15, verbose_name='State'),
        ),
    ]
