# Generated by Django 2.2.7 on 2020-02-06 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membermetric',
            old_name='is_over_fiftyfive',
            new_name='is_over_fifty_five',
        ),
    ]
