# Generated by Django 2.2.7 on 2020-02-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='text',
            field=models.CharField(db_index=True, help_text='The text content of this item type.', max_length=127, verbose_name='Text'),
        ),
    ]
