# Generated by Django 2.2.7 on 2020-02-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='uuid',
        ),
        migrations.AddField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(default='1', help_text='The unique identifier used externally.', max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
