# Generated by Django 3.0.7 on 2020-07-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacoordinator',
            name='indexed_text',
            field=models.CharField(blank=True, db_index=True, help_text='The searchable content text used by the keyword searcher function.', max_length=1023, null=True, unique=True, verbose_name='Indexed Text'),
        ),
        migrations.AddField(
            model_name='associate',
            name='indexed_text',
            field=models.CharField(blank=True, db_index=True, help_text='The searchable content text used by the keyword searcher function.', max_length=1023, null=True, unique=True, verbose_name='Indexed Text'),
        ),
        migrations.AddField(
            model_name='staff',
            name='indexed_text',
            field=models.CharField(blank=True, db_index=True, help_text='The searchable content text used by the keyword searcher function.', max_length=1023, null=True, unique=True, verbose_name='Indexed Text'),
        ),
    ]
