# Generated by Django 3.0.4 on 2020-03-26 03:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberaddress',
            name='needs_geolocating',
            field=models.BooleanField(blank=True, default=True, help_text='Field controls if system need to geolocate the current address to get a new longitude and latitude coordinates. Any address change results in this field being changed to `True`.', verbose_name='Needs Geolocating'),
        ),
        migrations.AddField(
            model_name='memberaddress',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
