# Generated by Django 2.2.7 on 2019-11-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermetric',
            name='already_registered',
            field=models.BooleanField(blank=True, default=False, help_text='Is there another member of your household which is registered with us?', verbose_name='Already registered with us?'),
        ),
    ]
