# Generated by Django 2.2.7 on 2020-02-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberaddress',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='memberaddress',
            name='region',
        ),
        migrations.AddField(
            model_name='memberaddress',
            name='city',
            field=models.CharField(default='London', help_text='The city. For example, Mountain View.', max_length=127, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberaddress',
            name='province',
            field=models.CharField(default='Ontario', help_text='The province. For example, CA.', max_length=127, verbose_name='Province'),
            preserve_default=False,
        ),
    ]
