# Generated by Django 2.2.7 on 2020-03-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermetric',
            name='year_of_birth',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='The year that this member was born in.', null=True, verbose_name='Year of Birth'),
        ),
    ]
