# Generated by Django 3.0.4 on 2020-04-01 03:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='boundry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text="The polygon of the watch's boundry.", null=True, srid=4326, verbose_name='Boundry'),
        ),
        migrations.AddField(
            model_name='watch',
            name='boundry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text="The polygon of the watch's boundry.", null=True, srid=4326, verbose_name='Boundry'),
        ),
    ]
