# Generated by Django 2.2.7 on 2019-11-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, help_text='The text content of this tag.', max_length=31, unique=True, verbose_name='Text')),
                ('description', models.TextField(blank=True, default='', help_text='A short description of this tag.', null=True, verbose_name='Description')),
                ('is_archived', models.BooleanField(blank=True, db_index=True, default=False, help_text='Indicates whether tag was archived.', verbose_name='Is Archived')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'nwapp_tags',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='member',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags associated with this member.', related_name='member_tags', to='tenant_foundation.Tag'),
        ),
    ]
