# Generated by Django 3.0.4 on 2020-03-28 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberaddress',
            old_name='needs_geolocating',
            new_name='needs_geocoding',
        ),
    ]
