# Generated by Django 2.2.7 on 2019-11-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.SlugField(default=1, help_text='The unique identifier used externally.', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
