# Generated by Django 2.2.7 on 2019-11-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='type_of',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Business'), (1, 'Residential'), (3, 'Community Cares')], db_index=True, help_text='The type of member this is.', verbose_name='Type of'),
        ),
        migrations.AlterField(
            model_name='membermetric',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Prefer not to say')], default=3, help_text='Gender of the person. While `Male` and `Female` may be used, text strings are also acceptable for people who do not identify as a binary gender.', verbose_name='Gender'),
        ),
    ]
