# Generated by Django 3.0.7 on 2020-08-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacoordinator',
            name='demotion_reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Retired'), (3, 'Health'), (4, 'No longer wants role'), (5, 'Reprimand'), (1, 'Other (Please specify)')], help_text='The reason for the demotion.', null=True, verbose_name='Demotion Reason'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='demotion_reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Retired'), (3, 'Health'), (4, 'No longer wants role'), (5, 'Reprimand'), (1, 'Other (Please specify)')], help_text='The reason for the demotion.', null=True, verbose_name='Demotion Reason'),
        ),
    ]
