# Generated by Django 3.0.4 on 2020-03-31 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membercomment',
            name='created_from_position',
        ),
    ]
