# Generated by Django 3.0.7 on 2021-01-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20210123_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='website_url',
            field=models.URLField(blank=True, default='', help_text='The URL to the website page.', null=True, verbose_name='Website URL'),
        ),
    ]
