# Generated by Django 3.0.4 on 2020-03-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20200326_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='governors',
            field=models.ManyToManyField(blank=True, help_text='The associates which are responsible for the operation of the district.', related_name='governing', to='tenant_foundation.Associate'),
        ),
        migrations.AddField(
            model_name='district',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags associated with this district.', related_name='districts', to='tenant_foundation.Tag'),
        ),
        migrations.AddField(
            model_name='watch',
            name='governors',
            field=models.ManyToManyField(blank=True, help_text='The area coordinator which are responsible for the operation of the district.', related_name='governing', to='tenant_foundation.AreaCoordinator'),
        ),
    ]
