# Generated by Django 2.2.7 on 2020-03-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20200319_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='archive_reason',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='archive_reason_other',
        ),
        migrations.AddField(
            model_name='watch',
            name='deactivation_reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'No Area Coordinator'), (3, 'Watch has collectively opted out of program'), (4, 'Watch Area not compliant'), (1, 'Other'), (0, 'Not specified')], default=0, help_text='The reason why this watch was deactivated.', verbose_name='Deactivation reason'),
        ),
        migrations.AddField(
            model_name='watch',
            name='deactivation_reason_other',
            field=models.CharField(blank=True, default='', help_text='The reason why this watch was deactivated which was not in the list.', max_length=2055, null=True, verbose_name='Deactivation reason (other)'),
        ),
    ]
