# Generated by Django 2.2.7 on 2020-02-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20200228_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateimageupload',
            name='description',
            field=models.TextField(blank=True, help_text='The text content of this upload.', null=True, verbose_name='Description'),
        ),
    ]
