# Generated by Django 2.2.7 on 2019-12-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20191220_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaddress',
            name='street_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Avenue'), (3, 'Drive'), (4, 'Road'), (5, 'Street'), (6, 'Way'), (1, 'Other')], help_text='Please select the street type.', verbose_name='Street Type'),
        ),
    ]
