# Generated by Django 2.2.7 on 2019-11-21 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20191121_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowHearAboutUsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, help_text='The text content of this item.', max_length=127, unique=True, verbose_name='Text')),
                ('sort_number', models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, help_text='The number this item will appear when sorted by number.', verbose_name='Sort #')),
                ('is_for_associate', models.BooleanField(blank=True, default=True, help_text='Indicates this option will be visible for the associate.', verbose_name='Is for associate')),
                ('is_for_customer', models.BooleanField(blank=True, default=True, help_text='Indicates this option will be visible for the customer.', verbose_name='Is for customer')),
                ('is_for_staff', models.BooleanField(blank=True, default=True, help_text='Indicates this option will be visible for the staff.', verbose_name='Is for staff')),
                ('is_for_partner', models.BooleanField(blank=True, default=True, help_text='Indicates this option will be visible for the partner.', verbose_name='Is for partner')),
                ('is_archived', models.BooleanField(blank=True, db_index=True, default=False, help_text='Indicates whether how hear item was archived.', verbose_name='Is Archived')),
            ],
            options={
                'verbose_name': 'How Hear About Us Item',
                'verbose_name_plural': 'How Hear About Us Items',
                'db_table': 'nwapp_how_hear_about_us_items',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, help_text='Gender of the person. While `Male` and `Female` may be used, text strings are also acceptable for people who do not identify as a binary gender.', max_length=31, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='member',
            name='year_of_birth',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='The year that this member was born in.', verbose_name='Year of Birth'),
        ),
        migrations.AddField(
            model_name='member',
            name='how_hear',
            field=models.ForeignKey(blank=True, help_text='How the member heard about the NWApp.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_how_hear_items', to='tenant_foundation.HowHearAboutUsItem'),
        ),
    ]
