# Generated by Django 2.2.7 on 2020-02-02 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_streetaddressrange_street_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='watch',
            field=models.ForeignKey(blank=True, help_text='The watch this member belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='tenant_foundation.Watch'),
        ),
    ]
