# Generated by Django 3.0.7 on 2020-08-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20200806_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaddress',
            name='street_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Avenue'), (3, 'Boulevard'), (4, 'Court'), (5, 'Crescent'), (6, 'Drive'), (7, 'Gate'), (8, 'Grove'), (9, 'Hill'), (10, 'Lane'), (11, 'Place'), (12, 'Road'), (13, 'Street'), (14, 'Terrace'), (15, 'Way'), (1, 'Other')], help_text='Please select the street type.', verbose_name='Street Type'),
        ),
    ]
