# Generated by Django 2.2.7 on 2020-01-29 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_watch_watchcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='text',
        ),
        migrations.AddField(
            model_name='watch',
            name='district',
            field=models.ForeignKey(default=1, help_text='The district whom this watch belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='tenant_foundation.District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch',
            name='name',
            field=models.CharField(db_index=True, default='1', help_text='The name of this watch.', max_length=63, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags associated with this watch.', related_name='watches', to='tenant_foundation.Tag'),
        ),
    ]
