# Generated by Django 2.2.7 on 2019-11-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_membermetric_already_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermetric',
            name='people_in_household_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='How many people are in your household?', verbose_name='People in Household Count'),
        ),
        migrations.AddField(
            model_name='membermetric',
            name='people_in_household_under_18_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='How many people in your household are under the age of 18?', verbose_name='People in Household under 18 Count'),
        ),
    ]
