# Generated by Django 2.2.7 on 2019-11-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20191126_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermetric',
            name='another_household_member_registered',
            field=models.BooleanField(default=False, help_text='Is there another member of your household which is registered with us?', null=True, verbose_name='Another Household Member Registered?'),
        ),
        migrations.AlterField(
            model_name='membermetric',
            name='organization_employee_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text="The employee count at this member's organization.", null=True, verbose_name='Organization Employee Count'),
        ),
        migrations.AlterField(
            model_name='membermetric',
            name='organization_founding_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The year this organization was founded.', null=True, verbose_name='Organization Founding Year'),
        ),
        migrations.AlterField(
            model_name='membermetric',
            name='total_household_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many people are in your household?', null=True, verbose_name='Total Household Count'),
        ),
        migrations.AlterField(
            model_name='membermetric',
            name='under_18_years_household_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many people in your household are under the age of 18?', null=True, verbose_name='Under 18 Years Household Count'),
        ),
    ]
