# Generated by Django 3.0.4 on 2020-04-01 04:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20200401_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='boundry',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='boundry',
        ),
        migrations.AddField(
            model_name='district',
            name='boundry_polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text="The polygon of the watch's boundry.", null=True, srid=4326, verbose_name='Boundry Polygon'),
        ),
        migrations.AddField(
            model_name='watch',
            name='boundry_polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text="The polygon of the watch's boundry.", null=True, srid=4326, verbose_name='Boundry Polygon'),
        ),
    ]
