# Generated by Django 2.2.7 on 2019-12-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20191129_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='indexed_text',
            field=models.CharField(blank=True, db_index=True, help_text='The searchable content text used by the keyword searcher function.', max_length=1023, null=True, unique=True, verbose_name='Indexed Text'),
        ),
    ]
