# Generated by Django 3.0.4 on 2020-03-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20200328_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberaddress',
            name='geocoding_failed_at',
            field=models.DateTimeField(blank=True, help_text='The date and time the geocding process failed.', null=True, verbose_name='Geocoding Failed At'),
        ),
        migrations.AddField(
            model_name='memberaddress',
            name='geocoding_succeeded_at',
            field=models.DateTimeField(blank=True, help_text='The date and time the geocding process succeeded.', null=True, verbose_name='Geocoding Succeeded At'),
        ),
    ]
