# Generated by Django 2.2.7 on 2020-01-13 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='counselor_phone',
            field=models.CharField(blank=True, help_text="The phone of this district's counselor.", max_length=31, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Counselor Phone'),
        ),
    ]
