# Generated by Django 2.2.7 on 2020-01-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_award_badge_scorepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='description_other',
            field=models.CharField(blank=True, help_text='The specific description for this award.', max_length=255, null=True, verbose_name='Description (Other)'),
        ),
        migrations.AddField(
            model_name='badge',
            name='description_other',
            field=models.CharField(blank=True, help_text='The specific description for this badge.', max_length=255, null=True, verbose_name='Description (Other)'),
        ),
        migrations.AlterField(
            model_name='award',
            name='type_of',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Weekly User'), (1, 'Other')], db_index=True, help_text='The type of score point this is.', verbose_name='Type of'),
        ),
        migrations.AlterField(
            model_name='scorepoint',
            name='type_of',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Neighbourhood Watch Donation'), (3, 'Daily Usage'), (1, 'Other')], db_index=True, help_text='The type of score point this is.', verbose_name='Type of'),
        ),
    ]
