# Generated by Django 3.0.7 on 2020-07-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20200718_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacoordinator',
            name='type_of',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Business'), (1, 'Residential'), (3, 'Community Cares')], db_index=True, default=1, help_text='The type of area coordinator this is.', verbose_name='Type of'),
        ),
        migrations.AddField(
            model_name='associate',
            name='type_of',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Business'), (1, 'Residential'), (3, 'Community Cares')], db_index=True, default=1, help_text='The type of area coordinator this is.', verbose_name='Type of'),
        ),
    ]
