# Generated by Django 3.0.4 on 2020-04-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_auto_20200403_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetaddressrange',
            name='street_number_range_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'All'), (2, 'Odd'), (3, 'Even')], default=1, help_text='Please select the street number range type.', verbose_name='Street Number Range Type'),
        ),
    ]
