# Generated by Django 3.0.4 on 2020-04-01 21:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_auto_20200401_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='boundry_position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text="The centre coordinates to apply for every map rendered on the user's screen.", null=True, srid=4326, verbose_name='Boundry Position'),
        ),
        migrations.AddField(
            model_name='district',
            name='boundry_zoom',
            field=models.FloatField(blank=True, help_text="The centre zoom to apply for every map rendered on the user's screen.", null=True, verbose_name='Boundry Map Zoom'),
        ),
    ]
