# Generated by Django 2.2.7 on 2020-01-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_auto_20200102_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorepoint',
            name='description_other',
            field=models.CharField(blank=True, help_text='The custom description associated with this score point.', max_length=255, null=True, verbose_name='Description (Other)'),
        ),
    ]
