# Generated by Django 2.2.7 on 2020-02-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_auto_20200223_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='has_accept_authority_cooperation',
            field=models.BooleanField(blank=True, default=False, help_text='Has user agreed to the fact that NW can contact the local and federal police services?', null=True, verbose_name='Has accepted authority cooperation'),
        ),
        migrations.AlterField(
            model_name='item',
            name='has_notified_authorities',
            field=models.BooleanField(blank=True, default=False, help_text='Has notified authorities?', null=True, verbose_name='Has notified authorities'),
        ),
    ]
