# Generated by Django 3.0.7 on 2020-07-18 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_auto_20200718_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacoordinator',
            name='watch',
            field=models.ForeignKey(blank=True, help_text='The watch this area coordinator belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_coordinators', to='tenant_foundation.Watch'),
        ),
        migrations.AddField(
            model_name='associate',
            name='watch',
            field=models.ForeignKey(blank=True, help_text='The watch this associate belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associates', to='tenant_foundation.Watch'),
        ),
    ]
