# Generated by Django 2.2.7 on 2019-11-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_auto_20191122_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membermetric',
            name='people_in_household_count',
        ),
        migrations.RemoveField(
            model_name='membermetric',
            name='people_in_household_under_18_count',
        ),
        migrations.AddField(
            model_name='membermetric',
            name='total_household_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='How many people are in your household?', verbose_name='Total Household Count'),
        ),
        migrations.AddField(
            model_name='membermetric',
            name='under_18_years_household_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='How many people in your household are under the age of 18?', verbose_name='Under 18 Years Household Count'),
        ),
    ]
