# Generated by Django 2.2.7 on 2020-01-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_auto_20200110_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacoordinator',
            name='demotion_reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Some reason'), (3, 'Another reason'), (1, 'Other (Please specify)')], help_text='The reason for the demotion.', null=True, verbose_name='Demotion Reason'),
        ),
        migrations.AddField(
            model_name='areacoordinator',
            name='demotion_reason_other',
            field=models.TextField(blank=True, help_text='The other reason for the demotion.', null=True, verbose_name='Demotion Reason (Other)'),
        ),
    ]
