# Generated by Django 2.2.7 on 2020-02-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_privateimageupload_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateimageupload',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags associated with this private file uploads.', related_name='private_image_uploads', to='tenant_foundation.Tag'),
        ),
    ]
