# Generated by Django 2.2.7 on 2020-02-02 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_member_watch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membermetric',
            old_name='under_18_years_household_count',
            new_name='over_18_years_household_count',
        ),
    ]
