# Generated by Django 2.2.7 on 2020-01-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0004_scorepoint_description_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorepoint',
            name='description_other',
            field=models.CharField(blank=True, help_text='The custom description override by the staff if the `Other` type was selected for this score point.', max_length=255, null=True, verbose_name='Description (Other)'),
        ),
    ]
