# Generated by Django 2.2.7 on 2020-01-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0004_streetaddressrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='type_of',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Business'), (1, 'Residential'), (3, 'Community Cares')], db_index=True, default=1, help_text='The type of watch this is.', verbose_name='Type of'),
            preserve_default=False,
        ),
    ]
