# Generated by Django 2.2.7 on 2019-11-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0004_auto_20191122_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membermetric',
            name='already_registered',
        ),
        migrations.AddField(
            model_name='membermetric',
            name='another_household_member_registered',
            field=models.BooleanField(blank=True, default=False, help_text='Is there another member of your household which is registered with us?', verbose_name='Another Household Member Registered?'),
        ),
    ]
