# Generated by Django 2.2.7 on 2020-03-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0004_privateimageupload_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(blank=True, help_text='The date this item occured.', null=True, verbose_name='Date'),
        ),
    ]
