# Generated by Django 2.2.7 on 2020-02-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0005_watch_type_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='name',
            field=models.CharField(db_index=True, help_text='The name of this watch.', max_length=63, verbose_name='Name'),
        ),
    ]
