# Generated by Django 2.2.7 on 2020-02-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0005_auto_20200223_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Incident'), (3, 'Event'), (4, 'Concern'), (5, 'Information'), (6, 'Community News'), (7, 'Volunteer')], db_index=True, help_text='The category this type of belongs to.', verbose_name='Category'),
        ),
    ]
