# Generated by Django 2.2.7 on 2019-11-21 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_foundation', '0005_auto_20191121_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAddress',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tenant_foundation.Member')),
                ('country', models.CharField(help_text='The country. For example, USA. You can also provide the two-letter <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements">ISO 3166-1 alpha-2</a> country code.', max_length=127, verbose_name='Country')),
                ('region', models.CharField(help_text='The region. For example, CA.', max_length=127, verbose_name='Region')),
                ('locality', models.CharField(help_text='The locality. For example, Mountain View.', max_length=127, verbose_name='Locality')),
                ('street_number', models.CharField(blank=True, help_text='-', max_length=127, null=True, verbose_name='Street Number')),
                ('street_name', models.CharField(blank=True, help_text='-', max_length=127, null=True, verbose_name='Street Name')),
                ('apartment_unit', models.CharField(blank=True, help_text='-', max_length=127, null=True, verbose_name='Apartment Unit')),
                ('street_type', models.CharField(blank=True, help_text='-', max_length=127, null=True, verbose_name='Region')),
                ('street_type_other', models.CharField(blank=True, help_text='-', max_length=127, null=True, verbose_name='Street Type Other')),
                ('street_direction', models.CharField(blank=True, help_text='-', max_length=127, null=True, verbose_name='Street Direction')),
                ('postal_code', models.CharField(blank=True, help_text='-', max_length=32, null=True, verbose_name='Postal Code')),
                ('created_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the creator.', null=True, verbose_name='Created from')),
                ('created_from_is_public', models.BooleanField(blank=True, default=False, help_text='Is creator a public IP and is routable.', verbose_name='Is the IP ')),
                ('last_modified_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the modifier.', null=True, verbose_name='Last modified from')),
                ('last_modified_from_is_public', models.BooleanField(blank=True, default=False, help_text='Is modifier a public IP and is routable.', verbose_name='Is the IP ')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user whom created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_member_addresses', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user whom modified this object last.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_member_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Address',
                'verbose_name_plural': 'Member Addresses',
                'db_table': 'nwapp_member_addresses',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
