# Generated by Django 2.2.7 on 2020-01-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0005_auto_20200103_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorepoint',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags associated with this score point.', related_name='score_points', to='tenant_foundation.Tag'),
        ),
    ]
