# Generated by Django 2.2.7 on 2020-03-03 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0005_auto_20200301_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='The unique identifier used externally.', max_length=255, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comment', models.ForeignKey(help_text='The comment this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='item_comments', to='tenant_foundation.Comment')),
                ('item', models.ForeignKey(help_text='The item whom this comment is about.', on_delete=django.db.models.deletion.CASCADE, related_name='item_comments', to='tenant_foundation.Item')),
            ],
            options={
                'verbose_name': 'Item Comment',
                'verbose_name_plural': 'Item Comments',
                'db_table': 'nwapp_item_comments',
                'ordering': ['-created_at'],
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
