# Generated by Django 2.2.7 on 2020-02-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0006_auto_20200201_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetaddressrange',
            name='street_name',
            field=models.CharField(db_index=True, help_text='The name of the street.', max_length=63, verbose_name='Street Name'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='name',
            field=models.CharField(db_index=True, help_text='The name of this watch.', max_length=63, unique=True, verbose_name='Name'),
        ),
    ]
