# Generated by Django 2.2.7 on 2020-03-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0006_itemcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_archived',
        ),
    ]
