# Generated by Django 2.2.7 on 2019-11-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0006_auto_20191122_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membermetric',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='membermetric',
            name='willing_to_volunteer',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No'), (2, 'Maybe')], default=2, help_text='Are you willing to willing_to_volunteer as a area coordinator / associate', verbose_name='Willing to willing_to_volunteer?'),
        ),
    ]
