# Generated by Django 2.2.7 on 2019-11-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0006_memberaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='apartment_unit',
        ),
        migrations.RemoveField(
            model_name='member',
            name='country',
        ),
        migrations.RemoveField(
            model_name='member',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='member',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='member',
            name='region',
        ),
        migrations.RemoveField(
            model_name='member',
            name='street_direction',
        ),
        migrations.RemoveField(
            model_name='member',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='street_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='street_type',
        ),
        migrations.RemoveField(
            model_name='member',
            name='street_type_other',
        ),
    ]
