# Generated by Django 2.2.7 on 2020-01-04 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0006_scorepoint_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='type_other',
            new_name='type_of_other',
        ),
    ]
