# Generated by Django 2.2.7 on 2019-12-31 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0006_privatefileupload_privateimageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatefileupload',
            name='slug',
            field=models.SlugField(default=1, help_text='The unique identifier used externally.', max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privateimageupload',
            name='slug',
            field=models.SlugField(default=1, help_text='The unique identifier used externally.', max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
