# Generated by Django 2.2.7 on 2020-02-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0006_auto_20200223_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='who_news_for',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'My City'), (3, 'My District'), (4, 'My Watch')], help_text='Whome shall see this news item?', null=True, verbose_name='Who news for?'),
        ),
    ]
