# Generated by Django 2.2.7 on 2019-11-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0007_auto_20191122_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='deactivation_reason_other',
            field=models.CharField(blank=True, default='', help_text='The reason why this member was deactivated which was not in the list.', max_length=2055, null=True, verbose_name='Deactivation reason (other)'),
        ),
        migrations.AlterField(
            model_name='membermetric',
            name='expectation_other',
            field=models.CharField(blank=True, default='Did not answer', help_text='-', max_length=2055, null=True, verbose_name='What do you expect from NW? (other)'),
        ),
        migrations.AlterField(
            model_name='membermetric',
            name='how_did_you_hear_other',
            field=models.CharField(blank=True, default='Did not answer', help_text='How member heared/learned about this NWApp.', max_length=2055, null=True, verbose_name='Learned about us (other)'),
        ),
        migrations.AlterField(
            model_name='membermetric',
            name='meaning_other',
            field=models.CharField(blank=True, default='Did not answer', help_text='-', max_length=2055, null=True, verbose_name='What does NW mean to you? (other)'),
        ),
    ]
