# Generated by Django 2.2.7 on 2020-01-25 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0007_resourceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceitem',
            name='text',
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Health'), (3, 'Housing'), (4, 'Loneliness'), (5, 'Food and Nutrition'), (6, 'Education'), (7, 'Municipal'), (8, 'Police'), (9, 'Fire'), (10, 'Emergency')], db_index=True, default=1, help_text='The type of score point this is.', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='description',
            field=models.TextField(blank=True, help_text='The description of this resource item.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='embed_code',
            field=models.TextField(blank=True, help_text='The embed code of this resource item.', null=True, verbose_name='Embed Code'),
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='file',
            field=models.ForeignKey(blank=True, help_text='The file of this resource item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_items', to='tenant_foundation.PrivateFileUpload'),
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='image',
            field=models.ForeignKey(blank=True, help_text='The image of this resource item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_items', to='tenant_foundation.PrivateImageUpload'),
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='name',
            field=models.CharField(db_index=True, default='TEST', help_text='The the name of this resource item.', max_length=31, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='type_of',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Link'), (3, 'YouTube Video'), (4, 'Image'), (5, 'File')], db_index=True, default=1, help_text='The type of score point this is.', verbose_name='Type of'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='website_url',
            field=models.URLField(blank=True, help_text='The external website link of this district.', max_length=255, null=True, verbose_name='Website URL'),
        ),
    ]
