# Generated by Django 2.2.7 on 2019-12-31 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0007_auto_20191231_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar_image',
            field=models.ForeignKey(blank=True, help_text='The avatar image of this member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='tenant_foundation.PrivateImageUpload'),
        ),
    ]
