# Generated by Django 2.2.7 on 2020-03-08 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tenant_foundation.models.task_item


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_foundation', '0007_remove_item_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Closed')], db_index=True, help_text='The state of task item.', verbose_name='State')),
                ('type_of', models.PositiveSmallIntegerField(choices=[(1, 'Assign Area Coordinator to Watch'), (2, 'Assign Associate to Watch'), (3, 'Action a NW concern item'), (4, 'Action a NW item item')], db_index=True, help_text='The type of task item this is.', verbose_name='Type of')),
                ('due_date', models.DateField(blank=True, db_index=True, default=tenant_foundation.models.task_item.get_todays_date, help_text='The date that this task must be finished by.', verbose_name='Due Date')),
                ('closing_reason', models.PositiveSmallIntegerField(blank=True, default=0, help_text='The reason for this task was closed.', null=True, verbose_name='Closing Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the creator.', null=True, verbose_name='Created from')),
                ('created_from_is_public', models.BooleanField(blank=True, default=False, help_text='Is creator a public IP and is routable.', verbose_name='Is the IP ')),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the modifier.', null=True, verbose_name='Last modified from')),
                ('last_modified_from_is_public', models.BooleanField(blank=True, default=False, help_text='Is modifier a public IP and is routable.', verbose_name='Is the IP ')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user whom created this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_items', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user whom last modified this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_task_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Item',
                'verbose_name_plural': 'Tas kItems',
                'db_table': 'nwapp_task_items',
                'ordering': ['due_date'],
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
