# Generated by Django 2.2.7 on 2020-01-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0008_auto_20200125_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceitem',
            name='website_url',
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='external_url',
            field=models.URLField(blank=True, help_text='The external website link of this resource item.', max_length=255, null=True, verbose_name='External URL'),
        ),
    ]
