# Generated by Django 2.2.7 on 2020-02-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0008_auto_20200224_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='format_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Link'), (3, 'YouTube Video'), (4, 'Image'), (5, 'File'), (6, 'Unspecified')], default=6, help_text='The format type of resource.', null=True, verbose_name='Format Type'),
        ),
    ]
