# Generated by Django 2.2.7 on 2019-11-23 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0008_auto_20191123_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaddress',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='address', serialize=False, to='tenant_foundation.Member'),
        ),
        migrations.AlterField(
            model_name='membercontact',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contact', serialize=False, to='tenant_foundation.Member'),
        ),
        migrations.AlterField(
            model_name='membermetric',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metric', serialize=False, to='tenant_foundation.Member'),
        ),
    ]
