# Generated by Django 2.2.7 on 2020-03-08 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0008_taskitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='closing_reason',
        ),
    ]
