# Generated by Django 2.2.7 on 2019-11-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0009_auto_20191123_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membermetric',
            name='organization_type_of',
        ),
        migrations.AddField(
            model_name='membercontact',
            name='organization_type_of',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Private'), (3, 'Government'), (4, 'Non-Profit'), (1, 'Unspecified')], default=1, help_text='The type of organization this is based on Neighbourhood Watch Canada internal classification.', verbose_name='Organization Type of'),
        ),
    ]
