# Generated by Django 2.2.7 on 2020-01-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0009_areacoordinator_associate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areacoordinator',
            old_name='code_of_conduct_agreement_agreement',
            new_name='code_of_conduct_agreement',
        ),
        migrations.RenameField(
            model_name='areacoordinator',
            old_name='conflict_of_interest_agreement_agreement',
            new_name='conflict_of_interest_agreement',
        ),
        migrations.RemoveField(
            model_name='areacoordinator',
            name='confidentiality_agreement_agreement',
        ),
        migrations.AddField(
            model_name='areacoordinator',
            name='confidentiality_agreement',
            field=models.TextField(blank=True, help_text='The actual terms of confidentiality agreement the user agreed to when they signed.', null=True, verbose_name='Confidentiality agreement'),
        ),
    ]
