# Generated by Django 2.2.7 on 2020-03-08 23:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0009_remove_taskitem_closing_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='The unique identifier we want to release to the public to identify this task item.', verbose_name='UUID'),
        ),
    ]
