# Generated by Django 2.2.7 on 2020-02-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0009_item_format_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='embed_code',
            field=models.CharField(blank=True, default='', help_text='The YouTube embed code for this item.', max_length=1023, null=True, verbose_name='Embed Code'),
        ),
    ]
