# Generated by Django 2.2.7 on 2020-03-08 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0010_taskitem_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskitem',
            options={'default_permissions': (), 'ordering': ['due_date'], 'permissions': (), 'verbose_name': 'Task Item', 'verbose_name_plural': 'Task Items'},
        ),
    ]
