# Generated by Django 2.2.7 on 2020-02-26 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0010_item_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateimageupload',
            name='item',
            field=models.ForeignKey(blank=True, help_text='The item whom this image belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_image_uploads', to='tenant_foundation.Item'),
        ),
    ]
