# Generated by Django 2.2.7 on 2020-02-01 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0010_auto_20200201_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatefileupload',
            name='user',
            field=models.ForeignKey(default=1, help_text='The user whom this belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='private_file_uploads', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
