# Generated by Django 2.2.7 on 2020-02-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0011_auto_20200201_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='indexed_text',
            field=models.CharField(blank=True, db_index=True, help_text='The searchable content text used by the keyword searcher function.', max_length=1023, null=True, unique=True, verbose_name='Indexed Text'),
        ),
    ]
