# Generated by Django 2.2.7 on 2020-02-26 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0011_privateimageupload_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatefileupload',
            name='item',
            field=models.ForeignKey(blank=True, help_text='The items whom this file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_file_uploads', to='tenant_foundation.Item'),
        ),
    ]
