# Generated by Django 2.2.7 on 2020-01-01 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0011_auto_20200101_0354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associate',
            old_name='code_of_conduct_agreement_agreement',
            new_name='code_of_conduct_agreement',
        ),
        migrations.RenameField(
            model_name='associate',
            old_name='confidentiality_agreement_agreement',
            new_name='confidentiality_agreement',
        ),
        migrations.RenameField(
            model_name='associate',
            old_name='conflict_of_interest_agreement_agreement',
            new_name='conflict_of_interest_agreement',
        ),
    ]
