# Generated by Django 2.2.7 on 2020-03-09 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0011_auto_20200308_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='district',
            field=models.ForeignKey(blank=True, help_text='The district whom this task item belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_items', to='tenant_foundation.District'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags associated with this task item.', related_name='task_items', to='tenant_foundation.Tag'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='watch',
            field=models.ForeignKey(blank=True, help_text='The watch this task item belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_items', to='tenant_foundation.Watch'),
        ),
    ]
