# Generated by Django 2.2.7 on 2020-03-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0012_auto_20200309_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='indexed_text',
            field=models.CharField(blank=True, db_index=True, help_text='The searchable content text used by the keyword searcher function.', max_length=1023, null=True, unique=True, verbose_name='Indexed Text'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='type_of',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Assign Area Coordinator to Watch'), (2, 'Assign Associate to Watch'), (3, 'Assign Associate to District'), (4, 'Action a NW concern item'), (5, 'Action a NW item item')], db_index=True, help_text='The type of task item this is.', verbose_name='Type of'),
        ),
    ]
