# Generated by Django 2.2.7 on 2020-02-27 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0012_privatefileupload_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='logo_image',
            field=models.ForeignKey(blank=True, help_text='The logo image of this item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_items', to='tenant_foundation.PrivateImageUpload'),
        ),
        migrations.AddField(
            model_name='item',
            name='resource_file',
            field=models.ForeignKey(blank=True, help_text='The resource file of this item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_file_items', to='tenant_foundation.PrivateFileUpload'),
        ),
        migrations.AddField(
            model_name='item',
            name='resource_image',
            field=models.ForeignKey(blank=True, help_text='The resource image of this item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_image_items', to='tenant_foundation.PrivateImageUpload'),
        ),
    ]
