# Generated by Django 2.2.7 on 2020-02-27 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0013_auto_20200227_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='logo_image',
        ),
        migrations.AddField(
            model_name='item',
            name='event_logo_image',
            field=models.ForeignKey(blank=True, help_text='The logo image of this event item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logo_items', to='tenant_foundation.PrivateImageUpload'),
        ),
    ]
