# Generated by Django 2.2.7 on 2020-03-09 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0014_auto_20200309_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='next_task_item',
            field=models.ForeignKey(blank=True, help_text='The next task item that belongs to this task item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenant_foundation.TaskItem'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='previous_task_item',
            field=models.ForeignKey(blank=True, help_text='The previous task item that belongs to this task item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenant_foundation.TaskItem'),
        ),
    ]
