# Generated by Django 2.2.7 on 2020-03-09 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0015_auto_20200309_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='item',
            field=models.ForeignKey(blank=True, help_text='The item this task item belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_items', to='tenant_foundation.Item'),
        ),
    ]
