from tenant_member.permissions.member_address_permissions import CanListCreateMemberAddressPermission, CanRetrieveUpdateDestroyMemberAddressPermission
from tenant_member.permissions.member_contact_permissions import CanListCreateMemberContactPermission, CanRetrieveUpdateDestroyMemberContactPermission
from tenant_member.permissions.member_comment_permissions import CanListCreateMemberCommentPermission, CanRetrieveUpdateDestroyMemberCommentPermission
from tenant_member.permissions.member_metric_permissions import CanListCreateMemberMetricPermission, CanRetrieveUpdateDestroyMemberMetricPermission
from tenant_member.permissions.member_file_upload_permissions import CanListCreateMemberFileUploadPermission, CanRetrieveUpdateDestroyMemberFileUploadPermission
from tenant_member.permissions.member_permissions import CanListCreateMemberPermission, CanRetrieveUpdateDestroyMemberPermission
