from tenant_member.permissions.address_permissions import CanListCreateMemberAddressPermission, CanRetrieveUpdateDestroyMemberAddressPermission
from tenant_member.permissions.contact_permissions import CanListCreateMemberContactPermission, CanRetrieveUpdateDestroyMemberContactPermission
from tenant_member.permissions.comment_permissions import CanListCreateMemberCommentPermission, CanRetrieveUpdateDestroyMemberCommentPermission
from tenant_member.permissions.metric_permissions import CanListCreateMemberMetricPermission, CanRetrieveUpdateDestroyMemberMetricPermission
from tenant_member.permissions.file_upload_permissions import CanListCreateMemberFileUploadPermission, CanRetrieveUpdateDestroyMemberFileUploadPermission
from tenant_member.permissions.base_permissions import CanListCreateMemberPermission, CanRetrieveUpdateDestroyMemberPermission
