from tenant_watch.views.list_create_view import WatchListCreateAPIView
from tenant_watch.views.retrieve_destroy_view import WatchRetrieveDestroyAPIView
from tenant_watch.views.comment_views import WatchCommentListCreateAPIView
from tenant_watch.views.update_info_views import WatchInformationUpdateAPIView
from tenant_watch.views.update_street_views import WatchStreetMembershipUpdateAPIView
from tenant_watch.views.archive_operation_views import WatchArchiveOperationAPIView
