from tenant_associate.permissions.comment_permissions import CanListCreateAssociateCommentPermission, CanRetrieveUpdateDestroyAssociateCommentPermission
from tenant_associate.permissions.file_upload_permissions import CanListCreateAssociateFileUploadPermission, CanRetrieveUpdateDestroyAssociateFileUploadPermission
from tenant_associate.permissions.base_permissions import CanListCreateAssociatePermission, CanRetrieveUpdateDestroyAssociatePermission
from tenant_associate.permissions.node_permissions import CanListCreateAssociateNodePermission, CanRetrieveUpdateDestroyAssociateNodePermission
