from tenant_associate.permissions.address_permissions import CanListCreateAssociateAddressPermission, CanRetrieveUpdateDestroyAssociateAddressPermission
from tenant_associate.permissions.contact_permissions import CanListCreateAssociateContactPermission, CanRetrieveUpdateDestroyAssociateContactPermission
from tenant_associate.permissions.comment_permissions import CanListCreateAssociateCommentPermission, CanRetrieveUpdateDestroyAssociateCommentPermission
from tenant_associate.permissions.metric_permissions import CanListCreateAssociateMetricPermission, CanRetrieveUpdateDestroyAssociateMetricPermission
from tenant_associate.permissions.file_upload_permissions import CanListCreateAssociateFileUploadPermission, CanRetrieveUpdateDestroyAssociateFileUploadPermission
from tenant_associate.permissions.base_permissions import CanListCreateAssociatePermission, CanRetrieveUpdateDestroyAssociatePermission
