from tenant_area_coordinator.permissions.address_permissions import CanListCreateAreaCoordinatorAddressPermission, CanRetrieveUpdateDestroyAreaCoordinatorAddressPermission
from tenant_area_coordinator.permissions.contact_permissions import CanListCreateAreaCoordinatorContactPermission, CanRetrieveUpdateDestroyAreaCoordinatorContactPermission
from tenant_area_coordinator.permissions.comment_permissions import CanListCreateAreaCoordinatorCommentPermission, CanRetrieveUpdateDestroyAreaCoordinatorCommentPermission
from tenant_area_coordinator.permissions.metric_permissions import CanListCreateAreaCoordinatorMetricPermission, CanRetrieveUpdateDestroyAreaCoordinatorMetricPermission
from tenant_area_coordinator.permissions.file_upload_permissions import CanListCreateAreaCoordinatorFileUploadPermission, CanRetrieveUpdateDestroyAreaCoordinatorFileUploadPermission
from tenant_area_coordinator.permissions.base_permissions import CanListCreateAreaCoordinatorPermission, CanRetrieveUpdateDestroyAreaCoordinatorPermission
from tenant_area_coordinator.permissions.node_permissions import CanListCreateAreaCoordinatorNodePermission, CanRetrieveUpdateDestroyAreaCoordinatorNodePermission
