from tenant_area_coordinator.permissions.comment_permissions import CanListCreateAreaCoordinatorCommentPermission, CanRetrieveUpdateDestroyAreaCoordinatorCommentPermission
from tenant_area_coordinator.permissions.file_upload_permissions import CanListCreateAreaCoordinatorFileUploadPermission, CanRetrieveUpdateDestroyAreaCoordinatorFileUploadPermission
from tenant_area_coordinator.permissions.base_permissions import CanListCreateAreaCoordinatorPermission, CanRetrieveUpdateDestroyAreaCoordinatorPermission
from tenant_area_coordinator.permissions.node_permissions import CanListCreateAreaCoordinatorNodePermission, CanRetrieveUpdateDestroyAreaCoordinatorNodePermission
