# Generated by Django 3.0.7 on 2020-10-03 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedorganization',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address.', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sharedorganization',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='The Facebook URL of the organization.', max_length=255, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='sharedorganization',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='The Instagram URL of the organization.', max_length=255, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='sharedorganization',
            name='phone',
            field=models.CharField(blank=True, help_text='The telephone number used by the organization.', max_length=31, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='sharedorganization',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='The Twitter URL of the organization.', max_length=255, null=True, verbose_name='Twitter URL'),
        ),
        migrations.AddField(
            model_name='sharedorganization',
            name='website_url',
            field=models.URLField(blank=True, help_text='The website URL of the organization.', max_length=255, null=True, verbose_name='Website URL'),
        ),
        migrations.AddField(
            model_name='sharedorganization',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='The YouTube URL of the organization.', max_length=255, null=True, verbose_name='YouTube URL'),
        ),
    ]
