# Generated by Django 2.2.1 on 2019-05-29 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareduser',
            name='tenant',
            field=models.ForeignKey(default=1, help_text='The tenant this user belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shared_foundation.SharedOrganization'),
            preserve_default=False,
        ),
    ]
