# Generated by Django 2.2.7 on 2019-11-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedorganization',
            name='apartment_unit',
            field=models.CharField(blank=True, help_text='-', max_length=127, null=True, verbose_name='Apartment Unit'),
        ),
        migrations.AddField(
            model_name='sharedorganization',
            name='postalCode',
            field=models.CharField(blank=True, help_text='-', max_length=32, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='sharedorganization',
            name='street_direction',
            field=models.CharField(blank=True, help_text='-', max_length=127, null=True, verbose_name='Street Direction'),
        ),
        migrations.AddField(
            model_name='sharedorganization',
            name='street_name',
            field=models.CharField(blank=True, help_text='-', max_length=127, null=True, verbose_name='Street Name'),
        ),
        migrations.AddField(
            model_name='sharedorganization',
            name='street_number',
            field=models.CharField(blank=True, help_text='-', max_length=127, null=True, verbose_name='Street Number'),
        ),
        migrations.AddField(
            model_name='sharedorganization',
            name='street_type',
            field=models.CharField(blank=True, help_text='-', max_length=127, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='sharedorganization',
            name='street_type_other',
            field=models.CharField(blank=True, help_text='-', max_length=127, null=True, verbose_name='Street Type Other'),
        ),
    ]
