# Generated by Django 3.0.4 on 2020-03-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedorganization',
            name='default_latitude',
            field=models.FloatField(blank=True, help_text="The centre latitude to apply for every map rendered on the user's screen.", null=True, verbose_name='Default Map Latitude'),
        ),
        migrations.AddField(
            model_name='sharedorganization',
            name='default_longitude',
            field=models.FloatField(blank=True, help_text="The centre longitude to apply for every map rendered on the user's screen.", null=True, verbose_name='Default Map Longitude'),
        ),
        migrations.AddField(
            model_name='sharedorganization',
            name='default_zoom',
            field=models.FloatField(blank=True, help_text="The centre zoom to apply for every map rendered on the user's screen.", null=True, verbose_name='Default Map Zoom'),
        ),
    ]
