# Generated by Django 2.2.7 on 2020-03-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedorganization',
            name='police_report_url',
            field=models.URLField(blank=True, help_text='The URL of the police reporting service used to submit crime reports.', max_length=255, null=True, verbose_name='Police Report URL'),
        ),
    ]
