# Generated by Django 2.2.1 on 2019-05-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0002_auto_20190529_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedorganization',
            name='id',
        ),
        migrations.AlterField(
            model_name='sharedorganization',
            name='schema',
            field=models.CharField(db_index=True, help_text='The schema name used for this organization.', max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Schema'),
        ),
    ]
