# Generated by Django 3.0.4 on 2020-03-29 20:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0002_auto_20200329_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedorganization',
            name='default_latitude',
        ),
        migrations.RemoveField(
            model_name='sharedorganization',
            name='default_longitude',
        ),
        migrations.AddField(
            model_name='sharedorganization',
            name='default_position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text="The centre coordinates to apply for every map rendered on the user's screen.", null=True, srid=4326, verbose_name='Default Position'),
        ),
    ]
