# Generated by Django 2.2.7 on 2019-11-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0002_auto_20191117_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedorganization',
            old_name='postalCode',
            new_name='postal_code',
        ),
    ]
