# Generated by Django 2.2.1 on 2019-05-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0002_auto_20190529_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedorganization',
            name='country',
            field=models.CharField(default=1, help_text='The country. For example, USA. You can also provide the two-letter <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements">ISO 3166-1 alpha-2</a> country code.', max_length=127, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedorganization',
            name='locality',
            field=models.CharField(default=1, help_text='The locality. For example, Mountain View.', max_length=127, verbose_name='Locality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedorganization',
            name='region',
            field=models.CharField(default=1, help_text='The region. For example, CA.', max_length=127, verbose_name='Region'),
            preserve_default=False,
        ),
    ]
