# Generated by Django 2.2.7 on 2019-11-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0003_sharedorganization_timezone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedorganization',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
