# Generated by Django 2.2.7 on 2019-11-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0003_auto_20191117_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareduser',
            name='slug',
            field=models.SlugField(default=1, help_text='The unique identifier used externally.', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
