# Generated by Django 2.2.1 on 2019-05-29 00:24

from django.db import migrations, models
import shared_foundation.models.shared_organization


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0003_auto_20190529_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedorganization',
            name='name',
            field=models.CharField(help_text='The name this organization.', max_length=63, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sharedorganization',
            name='schema',
            field=models.CharField(db_index=True, help_text='The schema name used for this organization.', max_length=255, primary_key=True, serialize=False, unique=True, validators=[shared_foundation.models.shared_organization.validate_schema], verbose_name='Schema'),
        ),
    ]
