# Generated by Django 2.2.1 on 2019-05-29 00:33

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('shared_foundation', '0004_auto_20190529_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Shared Group',
                'verbose_name_plural': 'Shared Groups',
                'db_table': 'nwapp_shared_groups',
                'permissions': (),
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
