from tenant_private_file_upload.serializers.list_serializers import PrivateFileUploadListSerializer
from tenant_private_file_upload.serializers.create_serializers import PrivateFileUploadCreateSerializer
from tenant_private_file_upload.serializers.retrieve_serializers import PrivateFileUploadRetrieveSerializer
from tenant_private_file_upload.serializers.update_serializers import PrivateFileUploadUpdateSerializer
