from tenant_private_file_upload.serializers.list_serializers import PrivateFileUploadListSerializer
from tenant_private_file_upload.serializers.create_serializers import PrivateFileUploadCreateSerializer
