"""
python manage.py run_historic_csv_import_for_districts "london" ""
python manage.py run_historic_csv_import_for_watches "london" ""
python manage.py run_historic_csv_import_for_members "london" ""
"""
